### ISSUE TITLE
zabbix Database error

### ISSUE THREAD

**Issue by jiaosir-cn** [Websoft9/ansible-zabbix#13]
**Describe the bug**

Ip + 80 port access error after installation.

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [x] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [x] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

v5.2

**OS**

- [ ] Ubuntu18.x
- [x] Ubuntu20.x
- [ ] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [x] Aws
- [x] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

## Bug reproduce

ip + 80
### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here
![image](https://user-images.githubusercontent.com/76861519/111274641-32b34280-8670-11eb-97b8-141b51c0d806.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
Host  is blocked because of many connection errors;unblock with mysqladmin flush-hosts

**Comment by jiaosir-cn** [comment]
alter user 'zabbix'@'%' identified with mysql_native_password by 'password';

Just ok
