### ISSUE TITLE
support version5.4 

### ISSUE THREAD

**Issue by laozhou0731** [Websoft9/ansible-zabbix#17]
**What type of your feature request?**  

- [ ] Add new features
- [ ] Improve current features

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Additional context**

**Comment by jiaosir-cn** [comment]
aliyun ubuntu 20.04 test ok
```
Docker version 20.10.7, build f0df350
phpmyadmin version: "version": "5.1.1",
nginx version: nginx/1.20.1
zabbix version: 5.4
mysql version: 8.0.25-1debian10"
System version: Ubuntu 20.04
Image name: zabbixjiaosir-Ubuntu20.04

```
