### ISSUE TITLE
The task has been completed, but the test has not been passed. It doesn't work.

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-zabbix#20]
**Describe the bug**

**zabbix 5.2-centos-azure**  can not access the login page of Zabbix
![image](https://user-images.githubusercontent.com/54173243/155059913-33abc79f-f5a3-45b7-92c4-13327489b4bd.png)

```
"Docker version 20.10.12, build e91ed57",
        "phpmyadmin version: \"version\": \"5.1.3\",",
        "nginx version: nginx/1.20.2",
        "zabbix version: 5.2",
        "mysql version: 8.0.28-1debian10\"",
        "System version: CentOS 7.9",
        "Image name: websoft9-zabbix5.2-CentOS7.9"
```  
![image](https://user-images.githubusercontent.com/54173243/155059826-efe7105d-a093-48c5-8345-c2ee63d9f80f.png)
  

## Deployment method

- [ ] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [ ] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

zabbix 5.2-centos-azure

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
版本标号弄错，重新修改docker-compose.yml，docker-compose-XX.yml不需要

**Comment by zengxc-1996** [comment]
![image](https://user-images.githubusercontent.com/63622990/155935490-21d57ac7-a12a-415e-b842-7789f6fc9b93.png)

Please change this line:  
docker-compose.yml 
${VOLUMES_PATH_PREFIX}/usr/share/zabbix/modules:/usr/share/zabbix/modules:ro

**Comment by zengxc-1996** [comment]
docker-compose v2 和 docker-compose v1  语法存在部分差异，基本上上下兼容。

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/63622990/155935490-21d57ac7-a12a-415e-b842-7789f6fc9b93.png)

Please change this line:  
docker-compose.yml 
${VOLUMES_PATH_PREFIX}/usr/share/zabbix/modules:/usr/share/zabbix/modules:ro

**Comment by qiaofeng1227** [comment]
docker-compose v2 和 docker-compose v1 语法存在部分差异，基本上上下兼容。
