### ISSUE TITLE
待改进：如果数据库为MariaDB，默认空密码可以登录

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-zabbix#6]
空密码可以登录的原因以及应对方案：
https://mariadb.com/kb/en/library/authentication-plugin-unix-socket/

教训：update user set plugin='' where user='root'; 此方案会导致root无法使用任何数据库插件，不可行

**Comment by hliblack** [comment]
实现方法：删除user plugin这段配置（目前已删除），能够同时适应MySQL密码登录和MariaDB空密码登录。
